const fs = require("node:fs");
const vm = require("node:vm");
const assert = require("node:assert/strict");

vm.runInThisContext(fs.readFileSync("js/logic.js", "utf8"));
const L = globalThis.DashboardLogic;

// ponytail: one dependency-free check covers the date, sorting, transfer and totals logic.
assert.equal(L.daysBetween("2026-07-20", "2026-07-26"), 6, "跨天计算错误");
assert.equal(L.tripMoment({ startDate: "2026-07-20", endDate: "2026-07-26" }, new Date(2026, 6, 22)).value, 3, "旅行天数错误");
assert.equal(L.urgentTasks([
  { id: "later", dueAt: "2026-07-21", priority: "high", completed: false },
  { id: "first", dueAt: "2026-07-20", priority: "low", completed: false }
], {}, 1)[0].id, "first", "任务排序错误");
assert.equal(L.transferBuffer("2026-07-25", "20:00", "2026-07-26", "00:40"), 280, "转机缓冲计算错误");
assert.equal(L.transferBuffer("2026-07-25", "16:00", "2026-07-26", "00:20"), 500, "返程转机缓冲计算错误");
assert.equal(L.budgetTotals([{ id: "a", plannedAmount: 100, actualAmount: 80, paid: true, payer: "我" }], {}).actual, 80, "预算汇总错误");
assert.deepEqual(L.inboxCounts([{ status: "incoming" }, { status: "processing" }, { status: "verified" }, { status: "archived" }]), { pending: 2, verified: 2 }, "Inbox状态统计错误");

const dataContext = { window: {} };
vm.createContext(dataContext);
vm.runInContext(fs.readFileSync("data/trip-data.js", "utf8"), dataContext);
const data = dataContext.window.TRIP_DATA;
const requiredSections = ["meta", "travelers", "route", "flights", "hotels", "weatherLocations", "hotelRegistry", "flightRegistry", "travelInbox", "documentRegistry", "documentReadiness", "itinerary", "transportPlan", "foodRecommendations", "travelTips", "departureChecklist", "finalDepartureChecklist", "departureCountdown", "riskAlerts", "coupleMoments", "tasks", "packing", "documents", "budget", "emergency", "gallery", "alerts", "changeLog"];
requiredSections.forEach((key) => assert.ok(data[key], `缺少数据区块: ${key}`));
assert.equal(data.meta.version, "1.5.4", "版本未更新");
assert.equal(data.meta.versionName, "Realtime Travel Status", "版本名称未更新");
data.weatherLocations.forEach((item) => ["id", "name", "latitude", "longitude", "timezone", "sea_condition"].forEach((key) => assert.ok(key in item, `天气地点缺少 ${key}`)));
data.hotelRegistry.forEach((item) => ["hotel_name", "check_in", "check_out", "address", "check_time", "breakfast", "map_link", "status"].forEach((key) => assert.ok(key in item, `酒店Registry缺少 ${key}`)));
data.flightRegistry.forEach((item) => ["flight_number", "departure", "arrival", "status"].forEach((key) => assert.ok(key in item, `航班Registry缺少 ${key}`)));
assert.deepEqual([...data.travelInbox.items], [], "Travel Inbox不得包含真实文件");
assert.equal(data.travelInbox.visibility, "private-only", "Travel Inbox边界错误");
assert.deepEqual([...data.travelInbox.statuses], ["incoming", "processing", "verified", "archived"], "Travel Inbox状态错误");
assert.deepEqual([...data.travelInbox.entryFields], ["documentId", "fileName", "fileType", "category", "status", "createdAt", "verifiedAt"], "Travel Inbox索引字段错误");
assert.deepEqual([...data.travelInbox.supportedTypes], ["pdf", "image"], "Travel Inbox文件类型错误");
assert.equal(data.travelInbox.githubUploadsAllowed, false, "Travel Inbox不应允许上传文件到GitHub");
assert.deepEqual([...data.documentRegistry.supportedCategories], ["flight", "hotel", "immigration", "insurance", "transport", "receipt"], "Document Registry分类错误");
assert.deepEqual([...data.documentRegistry.resultFields], ["title", "provider", "date", "relatedTripItem", "status"], "Document Registry结果字段错误");
assert.deepEqual([...data.documentRegistry.items], [], "Document Registry不得包含真实资料");
assert.equal(data.documentReadiness.publicSummaryOnly, true, "Private-Public Bridge必须仅包含公开摘要");
assert.deepEqual([...data.documentReadiness.categories].map((item) => [item.id, item.readyCount, item.totalCount, item.status]), [["flights", 4, 4, "ready"], ["hotels", 5, 5, "ready"], ["immigration", 7, 7, "ready"], ["transport", 0, 0, "missing"]], "资料准备摘要错误");
assert.deepEqual([...data.documentReadiness.emergencyStatus].map((item) => [item.id, item.status]), [["passport", "saved"], ["visa", "saved"], ["arrival", "saved"]], "紧急资料状态错误");
assert.doesNotMatch(JSON.stringify(data.documentReadiness), /(fileName|relativePath|iCloud|documentNumber|orderNumber|qrCode|fileContent)/i, "Private-Public Bridge包含私人字段");
data.finalDepartureChecklist.forEach((item) => ["phase", "time", "task", "description", "priority", "completed"].forEach((key) => assert.ok(key in item, `最终检查项缺少 ${key}`)));
assert.equal(data.departureCountdown.daysRemaining, 1, "出发倒计时错误");
assert.equal(data.departureCountdown.todayFocusTasks.length, 4, "今日重点任务数量错误");
assert.equal(data.itinerary.length, 6, "每日行程数量错误");
data.itinerary.forEach((day) => ["date", "city", "theme", "keywords", "transport", "periods", "notes", "maps"].forEach((key) => assert.ok(key in day, `${day.id} 缺少 ${key}`)));
data.flights.concat(data.hotels).forEach((item) => assert.ok(["pending", "confirmed", "changed", "cancelled"].includes(item.status), `非法状态: ${item.id}`));
assert.equal(data.flights.find((flight) => flight.id === "flight-3u3995").departureTime, "09:40", "3U3995时间错误");
assert.equal(data.flights.find((flight) => flight.id === "flight-kl-bali").flightNumber, "OD306", "当前有效航班未更新为OD306");
assert.equal(data.flights.find((flight) => flight.id === "flight-bali-kl").flightNumber, "OD307", "OD307缺失");
assert.equal(data.flights.find((flight) => flight.id === "flight-3u3994").departureTime, "00:20", "3U3994时间错误");
data.transportPlan.flatMap((plan) => plan.legs).forEach((leg) => ["recommendedMode", "estimatedDuration", "reservationRequired", "budget"].forEach((key) => assert.ok(key in leg, `交通段缺少 ${key}`)));
data.foodRecommendations.forEach((item) => ["type", "reason", "budgetRange", "suitableTime"].forEach((key) => assert.ok(key in item, `餐饮推荐缺少 ${key}`)));
assert.equal(data.riskAlerts.length, 5, "旅行风险提醒数量错误");
assert.equal(data.coupleMoments.length, 6, "情侣拍照地点数量错误");
data.tasks.forEach((task) => ["id", "title", "category", "assignee", "priority", "dueAt", "completed", "notes"].forEach((key) => assert.ok(key in task, `任务 ${task.id} 缺少 ${key}`)));
data.budget.forEach((item) => ["category", "item", "currency", "plannedAmount", "actualAmount", "paid", "payer", "notes"].forEach((key) => assert.ok(key in item, `预算项缺少 ${key}`)));
const index = fs.readFileSync("index.html", "utf8");
const serviceWorker = fs.readFileSync("service-worker.js", "utf8");
const appSource = fs.readFileSync("js/app.js", "utf8");
assert.ok(index.indexOf("config/sync-config.js") < index.indexOf("js/sync.js") && index.indexOf("js/sync.js") < index.indexOf("js/app.js"), "同步脚本加载顺序错误");
assert.ok(index.indexOf("data/trip-data.js") < index.indexOf("data/offline-pack.js") && index.indexOf("data/offline-pack.js") < index.indexOf("js/app.js"), "Offline Pack脚本加载顺序错误");
assert.ok(index.indexOf("js/weather.js") < index.indexOf("js/app.js"), "天气脚本加载顺序错误");
assert.ok(index.indexOf("js/documents.js") < index.indexOf("js/app.js"), "私人资料脚本加载顺序错误");
assert.match(serviceWorker, /CACHE_VERSION = "v1\.5\.4"/, "Service Worker缓存版本未更新");
assert.match(serviceWorker, /config\/sync-config\.js/, "同步配置未加入离线缓存");
assert.match(serviceWorker, /js\/sync\.js/, "同步逻辑未加入离线缓存");
assert.match(serviceWorker, /js\/weather\.js/, "天气逻辑未加入离线缓存");
assert.match(serviceWorker, /js\/documents\.js/, "私人资料逻辑未加入离线缓存");
assert.match(serviceWorker, /data\/offline-pack\.js/, "Offline Pack未加入离线缓存");
assert.ok(appSource.indexOf("await checklistSync.push(change)") < appSource.indexOf("commitChecklistChanges([change], synced)"), "清单更新不是云端优先");
assert.match(appSource, /pendingChecklistSync/, "缺少离线同步队列");
assert.match(appSource, /syncUserName/, "缺少共享用户身份");
assert.match(appSource, /lastSyncedAt/, "缺少最后同步时间");
assert.match(appSource, /TravelWeather/, "天气模块未接入首页");
assert.match(appSource, /readinessBoard/, "Readiness Board未接入首页");
assert.match(appSource, /OFFLINE_PACK/, "Offline Pack状态卡未接入首页");
assert.match(appSource, /inbox\.pending/, "Travel Inbox待处理数量未接入首页");
assert.match(appSource, /inbox\.verified/, "Travel Inbox已确认数量未接入首页");
assert.match(appSource, /documentReadiness\.categories/, "Document Readiness Board未接入首页");
assert.match(appSource, /documentReadiness\.emergencyStatus/, "紧急资料状态未接入Emergency Center");
assert.match(appSource, /Document Center/, "私人资料中心未接入页面");
assert.match(appSource, /linkedDocumentBlock\("flights"/, "Flight Center未关联私人文件");
assert.match(appSource, /linkedDocumentBlock\("hotels"/, "Hotel Center未关联私人文件");
assert.match(appSource, /Immigration Center/, "缺少Immigration Center");
assert.ok(fs.existsSync("config/sync-config.example.js"), "缺少同步配置模板");
assert.ok(fs.existsSync("supabase/travel_documents.sql"), "缺少私人资料表与Storage策略");
console.log("dashboard logic: ok");
